#pragma once

enum TokenType {
    FOR, WHILE, IF, AND, RIGHT_BRACE, LEFT_BRACE,
    MINUS, PLUS, STAR, SLASH, MOD, IDENTIFIER, SEMICOLON,
    LITERAL, TRUE, FALSE, PRINT,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    LEFT_PAREN, RIGHT_PAREN,

    END_OF_FILE
};
